"""Python coverage analysis check."""

import re
import sys
import time
from pathlib import Path
from typing import Optional

from slopbucket.checks.base import BaseCheck, PythonCheckMixin
from slopbucket.core.result import CheckResult, CheckStatus


class PythonCoverageCheck(BaseCheck, PythonCheckMixin):
    """Python coverage analysis check.

    Analyzes coverage.xml generated by pytest to verify coverage threshold.
    Default threshold is 80%.
    """

    DEFAULT_THRESHOLD = 80

    @property
    def name(self) -> str:
        return "python-coverage"

    @property
    def display_name(self) -> str:
        return "📊 Python Coverage (80% threshold)"

    @property
    def depends_on(self):
        return ["python-tests"]

    def is_applicable(self, project_root: str) -> bool:
        return self.is_python_project(project_root)

    def run(self, project_root: str) -> CheckResult:
        """Analyze coverage data."""
        start_time = time.time()

        # Check for coverage.xml
        coverage_file = Path(project_root) / "coverage.xml"
        if not coverage_file.exists():
            return self._create_result(
                status=CheckStatus.FAILED,
                duration=time.time() - start_time,
                output="",
                error="coverage.xml not found",
                fix_suggestion="Run python-tests check first to generate coverage data",
            )

        # Get coverage report
        result = self._run_command(
            [sys.executable, "-m", "coverage", "report", "--fail-under=0"],
            cwd=project_root,
            timeout=30,
        )

        duration = time.time() - start_time

        # Parse coverage percentage
        coverage_pct = self._parse_coverage(result.output)

        threshold = self.config.get("threshold", self.DEFAULT_THRESHOLD)

        if coverage_pct is None:
            return self._create_result(
                status=CheckStatus.ERROR,
                duration=duration,
                output=result.output,
                error="Could not parse coverage percentage",
            )

        if coverage_pct < threshold:
            return self._create_result(
                status=CheckStatus.FAILED,
                duration=duration,
                output=result.output,
                error=f"Coverage {coverage_pct:.1f}% is below {threshold}% threshold",
                fix_suggestion=f"Add tests to increase coverage above {threshold}%",
            )

        return self._create_result(
            status=CheckStatus.PASSED,
            duration=duration,
            output=f"Coverage: {coverage_pct:.1f}% (threshold: {threshold}%)\n{result.output}",
        )

    def _parse_coverage(self, output: str) -> Optional[float]:
        """Parse coverage percentage from output."""
        # Look for TOTAL line with percentage
        match = re.search(r"TOTAL\s+\d+\s+\d+\s+(\d+(?:\.\d+)?)%", output)
        if match:
            return float(match.group(1))

        # Fallback: look for any percentage
        match = re.search(r"(\d+(?:\.\d+)?)%", output)
        if match:
            return float(match.group(1))

        return None
