"""Python coverage analysis check.

Output is designed to be prescriptive for AI agents:
- Shows exactly which lines need tests
- Removes meta-information that doesn't help fix the problem
- Provides copy-paste-ready line references
"""

import ast
import os
import re
import time
import xml.etree.ElementTree as ET  # nosec B405 - parsing our own pytest-cov output
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple, Union, cast

from slopmop.checks.base import (
    BaseCheck,
    CheckRole,
    ConfigField,
    Flaw,
    GateCategory,
    GateDiagnosticResult,
    GateLevel,
    RemediationChurn,
    ToolContext,
)
from slopmop.checks.constants import (
    SKIP_NOT_PYTHON_PROJECT,
    coverage_below_threshold_message,
    has_python_test_files,
    python_no_tests_fix_suggestion,
    skip_reason_no_test_files,
)
from slopmop.checks.mixins import PythonCheckMixin
from slopmop.constants import (
    COVERAGE_BELOW_THRESHOLD,
    COVERAGE_GUIDANCE_FOOTER,
    COVERAGE_MEETS_THRESHOLD,
    COVERAGE_STANDARDS_PREFIX,
    COVERAGE_XML_NOT_FOUND,
)
from slopmop.core.result import CheckResult, CheckStatus, Finding, FindingLevel

COVERAGE_THRESHOLD = 80
CI_BUFFER = 0.5  # CI environments get slight buffer for timing variance
COVERAGE_POLL_TIMEOUT = 10  # seconds to wait for coverage.xml
MAX_FILES_TO_SHOW = 5  # Limit files shown to avoid overwhelming output


def _wait_for_coverage_xml(path: str) -> bool:
    """Poll for coverage.xml to appear when running alongside python-tests.

    In parallel mode, python-tests may still be generating .coverage and
    coverage.xml when this check starts.
    """
    deadline = time.time() + COVERAGE_POLL_TIMEOUT
    while time.time() < deadline:
        if os.path.exists(path) and os.path.getsize(path) > 0:
            return True
        time.sleep(0.5)
    return False


def _get_compare_branch() -> str:
    """Resolve the branch to diff against.

    Precedence: COMPARE_BRANCH env → GITHUB_BASE_REF (set in PR CI) → origin/main.

    GITHUB_BASE_REF is a bare branch name (e.g. 'main'), not a remote
    tracking ref.  diff-cover needs 'origin/main' so it can resolve
    commits via 'origin/main...HEAD'.  We prefix automatically.
    """
    explicit = os.environ.get("COMPARE_BRANCH")
    if explicit:
        return explicit
    base_ref = os.environ.get("GITHUB_BASE_REF")
    if base_ref:
        return f"origin/{base_ref}"
    return "origin/main"


def _configured_test_dirs(raw_test_dirs: object) -> List[str]:
    if isinstance(raw_test_dirs, list):
        test_dirs: List[str] = []
        for item_any in cast(List[object], raw_test_dirs):
            if isinstance(item_any, str):
                test_dirs.append(item_any)
        return test_dirs
    return ["tests"]


def _coverage_data_diagnostics(
    project_root: str,
    *,
    verify_command: str,
    test_dirs: List[str],
) -> List[GateDiagnosticResult]:
    """Return doctor diagnostics for coverage-data prerequisites."""
    if not has_python_test_files(project_root, test_dirs):
        message = skip_reason_no_test_files(test_dirs)
        return [
            GateDiagnosticResult(
                severity="fail",
                summary=message,
                detail=python_no_tests_fix_suggestion(test_dirs, verify_command),
            )
        ]

    coverage_xml = Path(project_root) / "coverage.xml"
    if coverage_xml.exists() and coverage_xml.stat().st_size > 0:
        return []

    coverage_db = Path(project_root) / ".coverage"
    coverage_db_note = ""
    if coverage_db.exists():
        coverage_db_note = (
            "\n\nA .coverage data file exists, but coverage.xml is missing; "
            "generate XML output before running the coverage gate."
        )

    return [
        GateDiagnosticResult(
            severity="warn",
            summary="coverage.xml is missing",
            detail=(
                "Coverage gates read coverage.xml generated by "
                "overconfidence:untested-code.py. Run the tests gate first, "
                f"then rerun {verify_command}." + coverage_db_note
            ),
            fix_hint="sm swab -g overconfidence:untested-code.py",
        )
    ]


class PythonCoverageCheck(BaseCheck, PythonCheckMixin):
    """Python test coverage enforcement.

    Wraps coverage.py to verify project-wide coverage meets the
    threshold. Reads coverage.xml generated by the overconfidence:untested-code.py gate.
    Output is prescriptive: shows exactly which files and lines need
    tests, sorted by largest coverage gap first.

    Level: scour

    Configuration:
      threshold: 80 — industry standard for mature projects.
          Start lower (30-50) on legacy codebases and ramp up.
          See README "Gradual Ramp" section.

    Common failures:
      Below threshold: The output lists files and missing line
          ranges. Write tests that exercise those lines.
      coverage.xml not found: The overconfidence:untested-code.py gate must run first
          to generate coverage data.

    Re-check:
      sm swab -g overconfidence:coverage-gaps.py --verbose
    """

    tool_context = ToolContext.PROJECT
    role = CheckRole.FOUNDATION
    remediation_churn = RemediationChurn.DOWNSTREAM_CHANGES_UNLIKELY

    DEFAULT_THRESHOLD = 80

    @property
    def name(self) -> str:
        return "coverage-gaps.py"

    @property
    def display_name(self) -> str:
        return "📊 Coverage (Python, pytest-cov)"

    @property
    def gate_description(self) -> str:
        return "📊 Whole-repo coverage (80% default threshold)"

    @property
    def category(self) -> GateCategory:
        return GateCategory.OVERCONFIDENCE

    @property
    def flaw(self) -> Flaw:
        return Flaw.OVERCONFIDENCE

    @property
    def depends_on(self) -> List[str]:
        return ["overconfidence:untested-code.py"]

    @property
    def config_schema(self) -> List[ConfigField]:
        return [
            ConfigField(
                name="threshold",
                field_type="integer",
                default=80,
                description="Minimum coverage percentage required",
                min_value=0,
                max_value=100,
                permissiveness="higher_is_stricter",
            ),
        ]

    def is_applicable(self, project_root: str) -> bool:
        """Applicable to Python projects; run() enforces test presence."""
        return self.is_python_project(project_root)

    def skip_reason(self, project_root: str) -> str:
        """Return skip reason when coverage prerequisites are missing."""
        if not self.is_python_project(project_root):
            return SKIP_NOT_PYTHON_PROJECT
        return "Python coverage check not applicable"

    def diagnose(self, project_root: str) -> List[GateDiagnosticResult]:
        return _coverage_data_diagnostics(
            project_root,
            verify_command=self.verify_command,
            test_dirs=_configured_test_dirs(self.config.get("test_dirs", ["tests"])),
        )

    def run(self, project_root: str) -> CheckResult:
        """Analyze coverage data and provide prescriptive output.

        Instead of meta-information, outputs exactly which lines need tests.
        """
        start_time = time.time()
        test_dirs = self.config.get("test_dirs", ["tests"])
        if not has_python_test_files(project_root, test_dirs):
            message = skip_reason_no_test_files(test_dirs)
            return self._create_result(
                status=CheckStatus.FAILED,
                duration=time.time() - start_time,
                error=message,
                output=message,
                fix_suggestion=python_no_tests_fix_suggestion(
                    test_dirs, self.verify_command
                ),
                findings=[Finding(message=message, level=FindingLevel.ERROR)],
            )

        # PROJECT check: bail early when no project venv exists
        venv_warn = self.check_project_venv_or_warn(project_root, start_time)
        if venv_warn is not None:
            return venv_warn

        # Check for coverage.xml
        coverage_file = Path(project_root) / "coverage.xml"
        if not coverage_file.exists():
            return self._create_result(
                status=CheckStatus.FAILED,
                duration=time.time() - start_time,
                output="",
                error=COVERAGE_XML_NOT_FOUND,
                fix_suggestion="Run python-tests check first to generate coverage data",
                findings=[
                    Finding(message=COVERAGE_XML_NOT_FOUND, level=FindingLevel.ERROR)
                ],
            )

        # Get coverage report with missing lines
        result = self._run_command(
            [
                self.get_project_python(project_root),
                "-m",
                "coverage",
                "report",
                "--show-missing",
                "--fail-under=0",
            ],
            cwd=project_root,
            timeout=30,
        )

        duration = time.time() - start_time

        # Parse coverage percentage
        coverage_pct = self._parse_coverage(result.output)
        threshold = self.config.get("threshold", self.DEFAULT_THRESHOLD)

        if coverage_pct is None:
            return self._create_result(
                status=CheckStatus.ERROR,
                duration=duration,
                output=result.output,
                error="Could not parse coverage percentage",
            )

        if coverage_pct >= threshold:
            return self._create_result(
                status=CheckStatus.PASSED,
                duration=duration,
                output=COVERAGE_MEETS_THRESHOLD,
            )

        return self._build_failure(
            coverage_pct, threshold, result.output, duration, project_root
        )

    def _build_failure(
        self,
        coverage_pct: float,
        threshold: int,
        raw_output: str,
        duration: float,
        project_root: str,
    ) -> CheckResult:
        """Construct the below-threshold failure result with per-file findings.

        Each per-file finding gets a fix_strategy pointing at the
        conventional test-file location + the exact uncovered line range.
        We DON'T guess what the test should assert — only where to write
        it and which lines it must exercise.  Anything further is
        judgment the agent brings.

        The test-file convention used is ``tests/test_{stem}.py`` for
        ordinary modules, ``tests/test_{pkg}.py`` for ``__init__.py``
        (package name, not the literal "__init__").  When neither
        convention yields a sensible target — e.g. a top-level
        ``__init__.py`` with no meaningful parent — strategy stays
        None.  Better to say nothing than to guess a garbage path.
        """
        missing_files = self._parse_missing_lines(raw_output)
        prescriptive_output = self._format_prescriptive_output(
            coverage_pct, threshold, missing_files
        )

        per_file: List[Finding] = []
        for fp, _stmts, miss, ranges in missing_files:
            target = _test_file_for(fp)
            # Try AST resolution first for richer fix_strategy
            ast_strategy = _resolve_uncovered_range(project_root, fp, ranges)
            per_file.append(
                Finding(
                    message=f"{miss} uncovered lines: {ranges}",
                    file=fp,
                    fix_strategy=(
                        ast_strategy
                        if ast_strategy
                        else (
                            (
                                f"Add tests in {target} that exercise "
                                f"lines {ranges} of {fp}"
                            )
                            if target
                            else None
                        )
                    ),
                )
            )
        # Fallback when per-file parsing yields nothing (e.g. minimal
        # coverage output that only contains the TOTAL line).
        if not per_file:
            per_file = [
                Finding(
                    message=coverage_below_threshold_message(coverage_pct, threshold),
                )
            ]

        return self._create_result(
            status=CheckStatus.FAILED,
            duration=duration,
            output=prescriptive_output,
            error=COVERAGE_BELOW_THRESHOLD,
            fix_suggestion=(
                "Each uncovered range above is resolved to its "
                "enclosing function where possible. Write tests that "
                "exercise those paths. Verify with: " + self.verify_command
            ),
            findings=per_file,
        )

    def _parse_missing_lines(self, output: str) -> List[Tuple[str, int, int, str]]:
        """Parse missing line info from coverage report.

        Returns list of (file, stmts, missing_count, missing_lines).
        Sorted by missing_count descending (biggest gaps first).
        """
        results: List[Tuple[str, int, int, str]] = []
        # Pattern: filename  stmts  miss  [branch  brpart]  cover%  missing
        # With branch=false:  slopmop/sb.py   456    386    15%   45-67, 89
        # With branch=true:   slopmop/sb.py   456    386   100   20   15%   45-67, 89
        # (?:\s+\d+)* absorbs optional Branch/BrPart columns.
        pattern = re.compile(
            r"^(\S+\.py)\s+(\d+)\s+(\d+)(?:\s+\d+)*\s+\d+%\s+(.+)$", re.MULTILINE
        )

        for match in pattern.finditer(output):
            filepath = match.group(1)
            stmts = int(match.group(2))
            missing = int(match.group(3))
            missing_lines = match.group(4).strip()

            # Skip files with 100% coverage or no missing lines
            if missing > 0 and missing_lines:
                results.append((filepath, stmts, missing, missing_lines))

        # Sort by missing count (biggest gaps first)
        results.sort(key=lambda x: x[2], reverse=True)
        return results

    def _format_prescriptive_output(
        self,
        coverage_pct: float,
        threshold: int,
        missing_files: List[Tuple[str, int, int, str]],
    ) -> str:
        """Format prescriptive output telling exactly what to do.

        No meta-info, just: "Add tests for these lines"
        """
        lines: List[str] = []
        lines.append(
            COVERAGE_STANDARDS_PREFIX
            + "Add high-quality test coverage to the following areas:"
        )
        lines.append("")

        # Show top files with most missing coverage
        for filepath, _stmts, _missing, missing_lines in missing_files[
            :MAX_FILES_TO_SHOW
        ]:
            lines.append(f"  {filepath}")
            lines.append(f"    Lines: {missing_lines}")
            lines.append("")

        if len(missing_files) > MAX_FILES_TO_SHOW:
            remaining = len(missing_files) - MAX_FILES_TO_SHOW
            lines.append(f"  ... and {remaining} more files")
            lines.append("")

        lines.append(COVERAGE_GUIDANCE_FOOTER)
        lines.append("")

        return "\n".join(lines)

    def _parse_coverage(self, output: str) -> Optional[float]:
        """Parse coverage percentage from output."""
        # Look for TOTAL line with percentage.
        # (?:\s+\d+)* absorbs optional Branch/BrPart columns so this
        # works with or without branch = true in coverage config.
        match = re.search(r"TOTAL\s+\d+\s+\d+(?:\s+\d+)*\s+(\d+(?:\.\d+)?)%", output)
        if match:
            return float(match.group(1))

        # Fallback: look for any percentage
        match = re.search(r"(\d+(?:\.\d+)?)%", output)
        if match:
            return float(match.group(1))

        return None


def _parse_unified_diff(diff_text: str) -> Dict[str, Set[int]]:
    """Parse ``git diff --unified=0`` output into ``{file: {head_line, ...}}``.

    Walks the unified diff body and collects every ``+`` line, mapping it to
    its line number in the head revision (the ``+<start>,<count>`` side of
    the hunk header). Deletions and ``---``/``+++`` headers are ignored.
    Returns an empty dict for an empty diff. The path returned is the
    repo-relative head path (``b/`` prefix stripped).

    ``+++ `` is ambiguous: Git emits ``+++ b/path`` only immediately after a
    ``--- `` old-path header, but a *hunk* addition whose body begins with
    ``++`` appears as the same ``+++ ...`` prefix. We therefore treat ``+++ ``
    as a new-file header only in that post-``--- `` position.
    """
    result: Dict[str, Set[int]] = {}
    current_file: Optional[str] = None
    current_line = 0
    expecting_new_path_header = False
    for raw in diff_text.splitlines():
        if raw.startswith("--- "):
            expecting_new_path_header = True
            continue
        if raw.startswith("+++ ") and expecting_new_path_header:
            expecting_new_path_header = False
            path = raw[4:].strip()
            if path == "/dev/null":
                current_file = None
            else:
                current_file = path[2:] if path.startswith("b/") else path
            continue
        if raw.startswith("---"):
            continue
        if raw.startswith("+++ ") and current_file is not None:
            result.setdefault(current_file, set()).add(current_line)
            current_line += 1
            continue
        if raw.startswith("@@"):
            m = re.match(r"@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)?", raw)
            if m:
                current_line = int(m.group(1))
            continue
        if current_file is None:
            continue
        if raw.startswith("+"):
            result.setdefault(current_file, set()).add(current_line)
            current_line += 1
        elif raw.startswith("-"):
            # Deletion: does not consume a head-side line number.
            continue
        else:
            # Context line. ``--unified=0`` should not produce these, but
            # behave correctly if a caller invokes us with context > 0.
            current_line += 1
    return result


def _parse_coverage_xml_lines(xml_text: str) -> Dict[str, Dict[int, str]]:
    """Parse Cobertura ``coverage.xml`` into ``{filename: {line_no: status}}``.

    Status is one of ``"hit"``, ``"miss"``, ``"partial"``:
      * ``miss``    — ``hits == 0``
      * ``partial`` — ``hits > 0`` AND ``branch="true"`` AND
                      ``condition-coverage`` < 100% (i.e. some branches at
                      this line were never taken)
      * ``hit``     — otherwise

    Lines that are not statements (blank, comments, decorators on their
    own line) are simply absent from the per-line mapping; callers that
    intersect with a diff treat absent lines as non-executable and skip.

    The ``filename`` is the repo-relative path emitted by coverage.py
    (matches the path layout in ``git diff``).
    """
    result: Dict[str, Dict[int, str]] = {}
    root = ET.fromstring(xml_text)  # nosec B314 - trusted, our own pytest-cov output
    for cls in root.iter("class"):
        filename = cls.get("filename")
        if not filename:
            continue
        per_line = result.setdefault(filename, {})
        for line in cls.iter("line"):
            number_attr = line.get("number")
            hits_attr = line.get("hits")
            if number_attr is None or hits_attr is None:
                continue
            try:
                lineno = int(number_attr)
                hits = int(hits_attr)
            except ValueError:
                continue
            if hits == 0:
                per_line[lineno] = "miss"
                continue
            if line.get("branch") == "true":
                cond = line.get("condition-coverage") or ""
                m = re.match(r"(\d+)%", cond)
                if m and int(m.group(1)) < 100:
                    per_line[lineno] = "partial"
                    continue
            per_line[lineno] = "hit"
    return result


@dataclass
class _FileDiffCov:
    """Per-file diff-coverage breakdown.

    ``hits``/``misses``/``partials`` are sorted lists of head-side line
    numbers. Lines that were in the diff but absent from coverage data
    (non-statements like blank lines or comments) are dropped before the
    report is built and never appear here.
    """

    filename: str
    hits: List[int] = field(default_factory=lambda: [])
    misses: List[int] = field(default_factory=lambda: [])
    partials: List[int] = field(default_factory=lambda: [])

    @property
    def total(self) -> int:
        return len(self.hits) + len(self.misses) + len(self.partials)

    @property
    def percent(self) -> float:
        if self.total == 0:
            return 100.0
        return 100.0 * len(self.hits) / self.total


@dataclass
class _DiffCoverageReport:
    """Aggregate diff-coverage report across every file in the diff."""

    files: List[_FileDiffCov]
    compare_branch: str

    @property
    def total_hits(self) -> int:
        return sum(len(f.hits) for f in self.files)

    @property
    def total_misses(self) -> int:
        return sum(len(f.misses) for f in self.files)

    @property
    def total_partials(self) -> int:
        return sum(len(f.partials) for f in self.files)

    @property
    def total_lines(self) -> int:
        return self.total_hits + self.total_misses + self.total_partials

    @property
    def percent(self) -> float:
        if self.total_lines == 0:
            return 100.0
        return 100.0 * self.total_hits / self.total_lines


def _compute_diff_coverage(
    diff_lines: Dict[str, Set[int]],
    coverage: Dict[str, Dict[int, str]],
    compare_branch: str,
) -> _DiffCoverageReport:
    """Classify each diffed line as hit/miss/partial via ``coverage`` data.

    Files that don't appear in ``coverage`` (test files, non-Python files,
    files under coverage's ``omit``) are silently skipped, matching the
    behavior of ``diff-cover``. Within a tracked file, diffed lines that
    aren't statements (no entry in the per-line map) are also skipped.
    Files that end up with zero classified lines are dropped from the
    report so the output stays signal-only.
    """
    files: List[_FileDiffCov] = []
    for filename in sorted(diff_lines):
        cov_per_line = coverage.get(filename)
        if cov_per_line is None:
            continue
        report = _FileDiffCov(filename=filename)
        for lineno in sorted(diff_lines[filename]):
            status = cov_per_line.get(lineno)
            if status == "hit":
                report.hits.append(lineno)
            elif status == "miss":
                report.misses.append(lineno)
            elif status == "partial":
                report.partials.append(lineno)
        if report.total > 0:
            files.append(report)
    return _DiffCoverageReport(files=files, compare_branch=compare_branch)


def _compact_line_ranges(lines: List[int]) -> str:
    """Compact ``[1, 2, 3, 5, 7, 8]`` into ``"1-3,5,7-8"``.

    Input may be unsorted; output is sorted ascending. An empty input
    yields ``""``.
    """
    if not lines:
        return ""
    sorted_lines = sorted(set(lines))
    ranges: List[str] = []
    start = sorted_lines[0]
    prev = start
    for n in sorted_lines[1:]:
        if n == prev + 1:
            prev = n
            continue
        ranges.append(f"{start}-{prev}" if prev != start else f"{start}")
        start = prev = n
    ranges.append(f"{start}-{prev}" if prev != start else f"{start}")
    return ",".join(ranges)


def _format_diff_coverage_output(report: _DiffCoverageReport) -> str:
    """Render a human-readable diff-coverage summary.

    Layout intentionally mirrors the original ``diff-cover`` block so
    existing log scrapers and human muscle memory keep working, with a
    small augmentation: we now show ``Partial`` line numbers as a
    distinct bucket and add a ``Hit`` row in the totals.
    """
    lines: List[str] = []
    lines.append("-------------")
    lines.append("Diff Coverage (partial-aware)")
    lines.append(f"Diff: {report.compare_branch}...HEAD")
    lines.append("-------------")
    if not report.files:
        lines.append("No coverage-tracked changes to evaluate.")
    for f in report.files:
        miss_str = _compact_line_ranges(f.misses)
        partial_str = _compact_line_ranges(f.partials)
        suffix_parts: List[str] = []
        if miss_str:
            suffix_parts.append(f"Missing {miss_str}")
        if partial_str:
            suffix_parts.append(f"Partial {partial_str}")
        suffix = "; ".join(suffix_parts)
        if suffix:
            lines.append(f"{f.filename} ({f.percent:.1f}%): {suffix}")
        else:
            lines.append(f"{f.filename} (100.0%)")
    lines.append("-------------")
    lines.append(f"Total:    {report.total_lines} lines")
    lines.append(f"Hit:      {report.total_hits} lines")
    lines.append(f"Missing:  {report.total_misses} lines")
    lines.append(f"Partial:  {report.total_partials} lines")
    lines.append(f"Coverage: {report.percent:.1f}%")
    lines.append("-------------")
    return "\n".join(lines)


def _build_diff_coverage_findings(report: _DiffCoverageReport) -> List[Finding]:
    """One Finding per file that has any miss or partial line."""
    findings: List[Finding] = []
    for f in report.files:
        if not f.misses and not f.partials:
            continue
        bits: List[str] = [f"Coverage {f.percent:.1f}% on changed lines"]
        if f.misses:
            bits.append(f"missing {_compact_line_ranges(f.misses)}")
        if f.partials:
            bits.append(f"partial {_compact_line_ranges(f.partials)}")
        findings.append(
            Finding(
                message=" — ".join(bits),
                file=f.filename,
                level=FindingLevel.ERROR,
            )
        )
    return findings


class PythonDiffCoverageCheck(BaseCheck, PythonCheckMixin):
    """Coverage enforcement on changed files only — partial-aware.

    Reads ``coverage.xml`` (Cobertura) generated by the
    ``overconfidence:untested-code.py`` gate, intersects it with
    ``git diff --unified=0 <compare_branch>...HEAD`` to find lines added
    or modified on this branch, and classifies each diffed line as
    ``hit``/``miss``/``partial``:

      * ``miss``    — line was never executed (``hits == 0``).
      * ``partial`` — line was executed but at least one branch on the
                      line was not taken (``branch="true"`` and
                      ``condition-coverage`` < 100%).
      * ``hit``     — line executed and (if branched) all branches taken.

    Counting partials as **misses** in the percentage matches Codecov's
    ``codecov/patch`` semantics, so the two engines agree on the
    numerator for the same diff. (Targets may still differ — slop-mop's
    threshold is fixed at 80% by default; Codecov defaults to base
    coverage.)

    Level: scour (needs PR diff context)

    Configuration:
      Compare branch is resolved from: COMPARE_BRANCH env var,
      then GITHUB_BASE_REF (set in PR CI), then origin/main.
      Threshold: 80% on changed lines.

    Common failures:
      Changed lines below 80%: Write tests for the new code shown in the
          output. Each file lists missing lines and partial-branch lines
          separately — fix the misses with new tests, fix the partials
          by widening test inputs to take the other branch.
      No diff: Gate passes automatically.

    Re-check:
      sm scour -g myopia:just-this-once.py --verbose
    """

    level = GateLevel.SCOUR
    tool_context = ToolContext.PROJECT
    role = CheckRole.FOUNDATION

    @property
    def name(self) -> str:
        return "just-this-once.py"

    @property
    def display_name(self) -> str:
        return f"📈 Diff Coverage ({COVERAGE_THRESHOLD}%)"

    @property
    def gate_description(self) -> str:
        return "📈 Coverage on changed lines only (partial-aware)"

    @property
    def category(self) -> GateCategory:
        return GateCategory.MYOPIA

    @property
    def flaw(self) -> Flaw:
        return Flaw.MYOPIA

    @property
    def depends_on(self) -> List[str]:
        return ["overconfidence:untested-code.py"]

    def is_applicable(self, project_root: str) -> bool:
        """Applicable to Python projects; run() enforces test presence."""
        return self.is_python_project(project_root)

    def skip_reason(self, project_root: str) -> str:
        """Return reason for skipping when not a Python project."""
        if not self.is_python_project(project_root):
            return SKIP_NOT_PYTHON_PROJECT
        return "Diff coverage check not applicable"

    def diagnose(self, project_root: str) -> List[GateDiagnosticResult]:
        return _coverage_data_diagnostics(
            project_root,
            verify_command=self.verify_command,
            test_dirs=_configured_test_dirs(self.config.get("test_dirs", ["tests"])),
        )

    def run(self, project_root: str) -> CheckResult:
        start_time = time.time()

        early = self._check_prerequisites(project_root, start_time)
        if early is not None:
            return early

        coverage_file = os.path.join(project_root, "coverage.xml")
        compare_branch = _get_compare_branch()

        diff_result = self._run_command(
            [
                "git",
                "diff",
                "--unified=0",
                f"{compare_branch}...HEAD",
                "--",
                "*.py",
            ],
            cwd=project_root,
            timeout=30,
        )
        duration = time.time() - start_time

        if not diff_result.success:
            return self._create_result(
                status=CheckStatus.ERROR,
                duration=duration,
                output=diff_result.output,
                error=(
                    "git diff failed; ensure the compare branch "
                    f"({compare_branch}) is fetched."
                ),
            )

        diff_lines = _parse_unified_diff(diff_result.output)
        if not diff_lines:
            return self._create_result(
                status=CheckStatus.PASSED,
                duration=duration,
                output="No changed Python files to check coverage on.",
            )

        try:
            coverage_xml = Path(coverage_file).read_text(encoding="utf-8")
            coverage_data = _parse_coverage_xml_lines(coverage_xml)
        except (OSError, ET.ParseError) as exc:
            return self._create_result(
                status=CheckStatus.ERROR,
                duration=duration,
                error=f"Could not parse coverage.xml: {exc}",
                fix_suggestion="Re-run python-tests to regenerate coverage data.",
            )

        return self._evaluate_report(
            _compute_diff_coverage(diff_lines, coverage_data, compare_branch),
            duration,
        )

    def _check_prerequisites(
        self, project_root: str, start_time: float
    ) -> Optional[CheckResult]:
        """Return an early result if preconditions are unmet, else None."""
        test_dirs = self.config.get("test_dirs", ["tests"])
        if not has_python_test_files(project_root, test_dirs):
            message = skip_reason_no_test_files(test_dirs)
            return self._create_result(
                status=CheckStatus.FAILED,
                duration=time.time() - start_time,
                error=message,
                output=message,
                fix_suggestion=python_no_tests_fix_suggestion(
                    test_dirs, self.verify_command
                ),
                findings=[Finding(message=message, level=FindingLevel.ERROR)],
            )

        venv_warn = self.check_project_venv_or_warn(project_root, start_time)
        if venv_warn is not None:
            return venv_warn

        coverage_file = os.path.join(project_root, "coverage.xml")
        if not _wait_for_coverage_xml(coverage_file):
            return self._create_result(
                status=CheckStatus.ERROR,
                duration=time.time() - start_time,
                error=COVERAGE_XML_NOT_FOUND,
                fix_suggestion="Run python-tests first to generate coverage data",
            )
        return None

    def _evaluate_report(
        self,
        report: _DiffCoverageReport,
        duration: float,
    ) -> CheckResult:
        """Turn the computed report into a PASSED or FAILED result."""
        output = _format_diff_coverage_output(report)

        if not report.files or report.percent >= COVERAGE_THRESHOLD:
            return self._create_result(
                status=CheckStatus.PASSED,
                duration=duration,
                output=output,
            )

        findings = _build_diff_coverage_findings(report)
        if not findings:
            findings = [
                Finding(
                    message=f"Changed files have <{COVERAGE_THRESHOLD}% coverage",
                    level=FindingLevel.ERROR,
                )
            ]
        return self._create_result(
            status=CheckStatus.FAILED,
            duration=duration,
            output=output,
            error=f"Changed files have <{COVERAGE_THRESHOLD}% coverage",
            fix_suggestion=(
                "Misses need new tests; partials need test inputs that "
                "exercise the un-taken branch on the listed lines."
            ),
            findings=findings,
        )


def _test_file_for(source_path: str) -> Optional[str]:
    """Derive the conventional test-file path for a source module.

    Convention: ``foo/bar.py`` → ``tests/test_bar.py``.
    Package case: ``foo/bar/__init__.py`` → ``tests/test_bar.py`` (parent
    dir name — the package IS the unit under test, not the file literal).

    Returns None when no reasonable convention applies — a root-level
    ``__init__.py`` with no named parent, or a degenerate path.  Caller
    skips fix_strategy on None.  This is the no-guessing escape hatch:
    saying nothing is better than ``test___init__.py``.
    """
    p = Path(source_path)
    stem = p.stem
    if stem == "__init__":
        # Package __init__ — conventional test target is the package name
        pkg = p.parent.name
        if not pkg or pkg in (".", "/"):
            return None
        return f"tests/test_{pkg}.py"
    if not stem:
        return None
    return f"tests/test_{stem}.py"


def _first_range(ranges: str) -> Optional[Tuple[int, int]]:
    """Pick the first ``start-end`` (or single ``N``) chunk from a
    coverage ``missing`` string like ``"12-18, 42, 90-101"``.

    Returns ``None`` when nothing parses — never raises.  We use the
    FIRST range rather than all of them because fix_strategy text is a
    single sentence: pointing at one concrete block gives the agent a
    starting handle, and the full range list is already in ``message``.
    """
    for chunk in ranges.split(","):
        chunk = chunk.strip()
        m = re.match(r"^(\d+)(?:-(\d+))?$", chunk)
        if m:
            start = int(m.group(1))
            end = int(m.group(2)) if m.group(2) else start
            return start, end
    return None


def _characterise_block(func: ast.AST, start: int, end: int) -> Optional[str]:
    """Identify whether an uncovered range sits inside an ``except``
    clause or an ``if`` body — the two block types where the testing
    approach is obvious (trigger the exception / supply the branching
    input).  Returns a hint sentence or ``None``.
    """
    for node in ast.walk(func):
        lo = getattr(node, "lineno", None)
        hi = getattr(node, "end_lineno", None)
        if lo is None or hi is None:
            continue
        if lo <= start and end <= hi:
            if isinstance(node, ast.ExceptHandler):
                return " This is an except block — test by triggering " "the exception."
            if isinstance(node, ast.If):
                return (
                    " This is a conditional branch — test with input "
                    "that takes this path."
                )
    return None


def _resolve_uncovered_range(
    project_root: str, filepath: str, ranges: str
) -> Optional[str]:
    """Resolve an uncovered line range to its enclosing function name
    and, where possible, characterise the block type.

    Returns a fix_strategy string or ``None``.  ``None`` is honest:
    it means we couldn't locate the range inside a function (module-
    level code, unparseable file, file moved since coverage ran).
    Never guesses — a wrong function name is worse than no name.
    """
    span = _first_range(ranges)
    if span is None:
        return None
    start, end = span

    source_path = Path(project_root) / filepath
    try:
        source = source_path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except (OSError, SyntaxError, ValueError):
        return None

    enclosing: Optional[Union[ast.FunctionDef, ast.AsyncFunctionDef]] = None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            lo = node.lineno
            hi = getattr(node, "end_lineno", None)
            if hi is None:
                continue
            if lo <= start and end <= hi:
                if enclosing is None or lo > enclosing.lineno:
                    enclosing = node

    if enclosing is None:
        return None

    func_name = enclosing.name
    strategy = (
        f"Lines {start}-{end} in {func_name}() are uncovered. "
        f"Write a test that exercises this path."
    )
    hint = _characterise_block(enclosing, start, end)
    if hint:
        strategy += hint
    return strategy
