#!/bin/bash
# Slop-Mop Setup Script
#
# Sets up slop-mop for a project:
#   1. Creates/finds a Python venv
#   2. Installs all required dependencies
#   3. Creates a convenience `sm` wrapper in the parent project
#   4. Verifies all tools are working
#
# Usage (from parent project root):
#   ./slop-mop/scripts/setup.sh
#
# Or from within slop-mop:
#   ./scripts/setup.sh

set -euo pipefail

# ─── Resolve paths ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SLOP_MOP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(cd "$SLOP_MOP_DIR/.." && pwd)"

echo ""
echo "🧹 Slop-Mop Setup"
echo "============================================================"
echo "📂 Project root:  $PROJECT_ROOT"
echo "📂 Slop-mop dir:  $SLOP_MOP_DIR"
echo ""

# ─── Step 1: Find or create venv ──────────────────────────────────
VENV_DIR=""
if [ -d "$PROJECT_ROOT/venv" ]; then
    VENV_DIR="$PROJECT_ROOT/venv"
    echo "✅ Found existing venv: $VENV_DIR"
elif [ -d "$PROJECT_ROOT/.venv" ]; then
    VENV_DIR="$PROJECT_ROOT/.venv"
    echo "✅ Found existing venv: $VENV_DIR"
else
    VENV_DIR="$PROJECT_ROOT/venv"
    echo "📦 Creating virtual environment: $VENV_DIR"
    python3 -m venv "$VENV_DIR"
    echo "✅ Virtual environment created"
fi

PYTHON="$VENV_DIR/bin/python"
PIP="$VENV_DIR/bin/pip"

# Activate for the rest of this script
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

# ─── Step 2: Upgrade pip ──────────────────────────────────────────
echo ""
echo "📦 Upgrading pip..."
"$PYTHON" -m pip install --upgrade pip --quiet

# ─── Step 3: Install slop-mop dependencies ────────────────────────
echo ""
echo "📦 Installing slop-mop dependencies..."

# Use requirements.txt as the single source of truth for deps
REQUIREMENTS="$SLOP_MOP_DIR/requirements.txt"
if [ ! -f "$REQUIREMENTS" ]; then
    echo "❌ Error: requirements.txt not found at $REQUIREMENTS"
    exit 1
fi

"$PIP" install -r "$REQUIREMENTS" --quiet 2>&1 || {
    echo ""
    echo "⚠️  Some packages failed to install. Trying individually..."
    FAILED=()
    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue
        "$PIP" install "$line" --quiet 2>&1 || FAILED+=("$line")
    done < "$REQUIREMENTS"
    
    if [ ${#FAILED[@]} -gt 0 ]; then
        echo ""
        echo "❌ Failed to install these packages:"
        for pkg in "${FAILED[@]}"; do
            echo "   • $pkg"
        done
        echo ""
        echo "   These checks may not work until the packages are installed."
        echo "   You can try installing them manually or check platform compatibility."
    fi
}

echo "✅ Dependencies installed"

# ─── Step 4: Create convenience wrapper ───────────────────────────
echo ""
echo "📄 Creating 'sm' wrapper script..."

# Determine the relative path from project root to slop-mop
RELATIVE_SM_DIR=$(python3 -c "import os.path; print(os.path.relpath('$SLOP_MOP_DIR', '$PROJECT_ROOT'))")

SM_WRAPPER="$PROJECT_ROOT/scripts/sm"
mkdir -p "$(dirname "$SM_WRAPPER")"

cat > "$SM_WRAPPER" << WRAPPER_EOF
#!/bin/bash
# Auto-generated by slop-mop setup — runs sm from the local submodule.
# Do NOT install slop-mop via pip. Each project gets its own copy.

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="\$(cd "\$SCRIPT_DIR/.." && pwd)"
SLOP_MOP_DIR="\$PROJECT_ROOT/$RELATIVE_SM_DIR"

if [ ! -d "\$SLOP_MOP_DIR/slopmop" ]; then
    echo "❌ Error: slop-mop submodule not found at \$SLOP_MOP_DIR"
    echo "   Run: git submodule update --init"
    exit 1
fi

# Run the module directly from the submodule
export PYTHONPATH="\$SLOP_MOP_DIR:\${PYTHONPATH:-}"
exec "\$PROJECT_ROOT/venv/bin/python" -m slopmop.sm "\$@"
WRAPPER_EOF

chmod +x "$SM_WRAPPER"
echo "✅ Wrapper created: $SM_WRAPPER"

# Create root-level wrapper so `./sm` works from the project root.
# Same pattern as ./gradlew or ./manage.py — a real executable that
# delegates to the canonical scripts/sm wrapper.
ROOT_SM="$PROJECT_ROOT/sm"
if [ ! -e "$ROOT_SM" ] || [ -L "$ROOT_SM" ]; then
    # Remove stale symlink if present (migrating from earlier setup)
    [ -L "$ROOT_SM" ] && rm -f "$ROOT_SM"
    cat > "$ROOT_SM" << 'ROOT_WRAPPER_EOF'
#!/bin/bash
# Auto-generated by slop-mop setup — root-level convenience wrapper.
# Delegates to scripts/sm. Same pattern as ./gradlew or ./manage.py.
exec "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/scripts/sm" "$@"
ROOT_WRAPPER_EOF
    chmod +x "$ROOT_SM"
    echo "✅ Root wrapper created: $ROOT_SM (delegates to scripts/sm)"
else
    echo "⚠️  $ROOT_SM already exists — skipping (delete it to regenerate)"
fi

# ─── Step 5: Verify tools ────────────────────────────────────────
echo ""
echo "🔍 Verifying tool availability..."

TOOLS=(
    "black:black --version"
    "isort:isort --version"
    "flake8:flake8 --version"
    "mypy:mypy --version"
    "pyright:pyright --version"
    "pytest:pytest --version"
    "vulture:vulture --version"
    "bandit:bandit --version"
    "detect-secrets:detect-secrets --version"
    "semgrep:semgrep --version"
    "pip-audit:pip-audit --version"
    "autoflake:autoflake --version"
    "diff-cover:diff-cover --version"
)

PASS=0
FAIL=0
MISSING=()

for entry in "${TOOLS[@]}"; do
    IFS=: read -r name cmd <<< "$entry"
    if $cmd &>/dev/null; then
        ((PASS++))
    else
        ((FAIL++))
        MISSING+=("$name")
    fi
done

echo ""
echo "   ✅ $PASS tools available"
if [ $FAIL -gt 0 ]; then
    echo "   ⚠️  $FAIL tools not found:"
    for tool in "${MISSING[@]}"; do
        echo "      • $tool"
    done
    echo "   Some quality gates may be disabled until these are installed."
fi

# ─── Step 6: Done ─────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "🚀 Setup Complete!"
echo "============================================================"
echo ""
echo "Next steps (from project root):"
echo "  ./sm init              # Auto-detect project, write config"
echo "  ./sm validate commit   # Run quality gates"
echo "  ./sm config --show     # Review configuration"
echo ""
