#!/usr/bin/env python3
"""Summarize coverage.py XML output for CI step summaries."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Optional, Sequence

_LINE_RATE_RE = re.compile(r'line-rate="([0-9.]+)"')


def load_coverage_pct(xml_path: Path) -> float:
    """Return the total line coverage percentage from coverage.py XML."""
    try:
        xml_text = xml_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"Could not read coverage XML: {xml_path}") from exc

    match = _LINE_RATE_RE.search(xml_text)
    if match is None:
        raise ValueError("coverage XML missing line-rate attribute")
    line_rate = match.group(1)

    try:
        return float(line_rate) * 100.0
    except ValueError as exc:
        raise ValueError(f"Invalid coverage line-rate: {line_rate}") from exc


def find_total_line(report_path: Optional[Path]) -> Optional[str]:
    """Return the TOTAL line from a coverage report, if present."""
    if report_path is None or not report_path.exists():
        return None

    for line in report_path.read_text(encoding="utf-8").splitlines():
        if line.lstrip().startswith("TOTAL"):
            return line.strip()
    return None


def build_summary(coverage_pct: float, total_line: Optional[str]) -> str:
    """Build markdown suitable for a GitHub Actions step summary."""
    lines = [
        "## Unit Test Coverage",
        "",
        f"- Total line coverage: {coverage_pct:.1f}%",
    ]
    if total_line:
        lines.append(f"- coverage.py summary: `{total_line}`")
    return "\n".join(lines) + "\n"


def write_step_summary(path: Optional[str], summary: str) -> None:
    """Append coverage summary markdown to the GitHub step summary file."""
    if not path:
        return
    summary_path = Path(path)
    with summary_path.open("a", encoding="utf-8") as handle:
        handle.write(summary)


def parse_coverage_summary_args(
    argv: Optional[Sequence[str]] = None,
) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml", required=True, help="Path to coverage.xml")
    parser.add_argument(
        "--report",
        help="Optional text report generated by coverage/pytest for TOTAL-line context",
    )
    parser.add_argument(
        "--step-summary-path",
        help="Optional path to the GitHub Actions step summary file",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_coverage_summary_args(argv)
    try:
        coverage_pct = load_coverage_pct(Path(args.xml))
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    total_line = find_total_line(Path(args.report)) if args.report else None
    summary = build_summary(coverage_pct, total_line)
    write_step_summary(args.step_summary_path, summary)
    print(f"Coverage {coverage_pct:.1f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
